import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import Nav from "../components/ui/myNavbar"

import  PageTransition  from "../components/ui/pageTransition";
import StairTransition from "../components/ui/StairTransition";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black pb-7">
      <body className={inter.className}>
        <Nav />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
        </body>
    </html>
  );
}
